const EmployeeType = {
  FETCH_EMPLOYEE_START: 'FETCH_EMPLOYEE_START',
  FETCH_EMPLOYEE_SUCCESS: 'FETCH_EMPLOYEE_SUCCESS',
  FETCH_EMPLOYEE_FAIL: 'FETCH_EMPLOYEE_FAIL',

  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  SAVE_CREATE_EMPLOYEE_START: 'SAVE_CREATE_EMPLOYEE_START',
  SAVE_CREATE_EMPLOYEE_SUCCESS: 'SAVE_CREATE_EMPLOYEE_SUCCESS',
  SAVE_CREATE_EMPLOYEE_FAIL: 'SAVE_CREATE_EMPLOYEE_FAIL',
  
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  SAVE_DELETE_EMPLOYEE_START: 'SAVE_DELETE_EMPLOYEE_START',
  SAVE_DELETE_EMPLOYEE_SUCCESS: 'SAVE_DELETE_EMPLOYEE_SUCCESS',
  SAVE_DELETE_EMPLOYEE_FAIL: 'SAVE_DELETE_EMPLOYEE_FAIL',

  EDIT_EMPLOYEE_START: 'EDIT_EMPLOYEE_START',
  EDIT_EMPLOYEE_SUCESS: 'EDIT_EMPLOYEE_SUCESS',
  EDIT_EMPLOYEE_FAIL: 'EDIT_EMPLOYEE_FAIL'
}

export default EmployeeType